package com.nde.shopmanagement.exceptions;

public enum ErrorCodes {

    ITEM_NOT_FOUND(1000),
    ITEM_NOT_VALID(1001),
    CATEGORY_NOT_FOUND(2000),
    // TODO complete the rest of error Codes
    CUSTOMER_NOT_FOUND(1000),
    CUSTOMER_ORDER_NOT_VALID(1002),
    CUSTOMER_ORDER_NOT_FOUND(1003),
    ORDER_NOT_FOUND(2000),
    SUPPLIER_COMMAND_NOT_FOUND(1000),
    BUSINESS_NOT_FOUND(2000),
    SUPPLIER_NOT_FOUND(1000),
    SUPPLIER_ORDER_NOT_VALID(1001),
    SUPPLIER_ORDER_NOT_FOUND(1000),
    CUSTOMER_ORDER_LINE_NOT_FOUND(2000),
    SUPPLIER_ORDER_LINE_NOT_FOUND(1000),
    SALE_LINE_NOT_FOUND(2000),
    INVENTORY_NOT_FOUND(1000),
    INVENTORY_NOT_VALID(1001),
    USER_NOT_FOUND(2000),
    SALE_NOT_FOUND(1000),
    SALE_NOT_VALID(1001),
    ;

    private int code;

    ErrorCodes(int code){

    }
}
